apiVersion: v1
kind: Pod
metadata:
  name: evicted-pod
spec:
  containers:
    - name: memory-hog
      image: busybox
      command: ["sh", "-c", "dd if=/dev/zero of=/dev/null"]
      resources:
        limits:
          memory: "10Mi"
      imagePullPolicy: IfNotPresent
