apiVersion: v1
kind: Pod
metadata:
  name: failed-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "exit 1"]  # Causes immediate failure
      restartPolicy: Never
